### ISSUE TITLE
Problems Setting up the dataset

### ISSUE THREAD

**Issue by prerit1998jain** [jvlmdr/trackdat#1]
`tar: tar/original/vot2018.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
`

This error pops up as I run the command, 
'tar -cf tar/original/vot2018.tar -C $temp vot2018'

**Comment by jvlmdr** [comment]
Hi. This error occurred because the directory `tar/original/` did not exist. I have added a `mkdir -p` command to the example:
https://github.com/jvlmdr/trackdat/commit/aaeaa7bd8d228aa9f43b257fc343ab856b68d02b

This should fix the problem.
