### ISSUE TITLE
have some problem

### ISSUE THREAD

**Issue by PKQ1688** [jvlmdr/trackdat#3]
2020-09-01 14:26:30 (69.7 KB/s) - ‘description.json’ saved [64700/64700]

scripts/download_vot.sh: line 19: jq: command not found
scripts/download_vot.sh: line 20: jq: command not found
scripts/download_vot.sh: line 21: jq: command not found

**Comment by eslambakr** [comment]
This works for me:
sudo apt install jq

**Comment by jvlmdr** [comment]
Yes, it depends on [jq](https://stedolan.github.io/jq/) to parse the JSON files for VOT.
