### ISSUE TITLE
problem about "Problems Setup datasets'"

### ISSUE THREAD

**Issue by Gi-gigi** [jvlmdr/trackdat#5]
when i run `VOT_YEAR=2018 bash scripts/download_vot.sh dl/vot2018`
there is nothing file in `annotations` and so on.

- 
scripts/download_vot.sh: 行 19: jq: 未找到命令
scripts/download_vot.sh: 行 20: jq: 未找到命令
scripts/download_vot.sh: 行 21: jq: 未找到命令
`
    cat description.json | jq -r '.sequences[] | .annotations.url' >annotations.txt
    cat description.json | jq -r '.sequences[] | .channels.color.url' >color.txt
    cat description.json | jq -r '.sequences[] | .name' >list.txt
    mkdir -p annotations
`
can anyone give some advice, thank u!~~~

**Comment by Gi-gigi** [comment]
Hi @jvlmdr ,sir
I met some probelm
```
scripts/download_vot.sh: 行 19: jq：command not found
scripts/download_vot.sh: 行 20: jq：command not found
scripts/download_vot.sh: 行 21: jq：command not found
```
can u give me some advice? thank u sir

**Comment by jvlmdr** [comment]
You need [jq](https://stedolan.github.io/jq/)

On ubuntu, do `apt-get install jq`, or on macos do `brew install jq`
